name: Build

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      type:
        description: alpha or beta
        default: alpha



jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: "src"

      - name: Determine channel
        id: channel
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            channel="dev"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ inputs.type }}" == "alpha" ]; then
              channel="alpha"
            elif [ "${{ inputs.type }}" == "beta" ]; then
              channel="beta"
            else
              channel="dev"
            fi
          else
            channel="stable"
          fi
          echo "Channel: $channel"
        shell: bash

      - name: Checkout builds-$channel
        uses: actions/checkout@v2
        with:
          ref: "builds-$channel"
          path: "builds-$channel"

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle


      - name: Build with Gradle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew build
          cp app/build/outputs/apk/release/app-release.apk ../builds-$channel/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk
      - name: Push builds-dev
        run: |
          cd $GITHUB_WORKSPACE/builds-$channel
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push