name: Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: "src"

    - name: Checkout builds
      uses: actions/checkout@v2
      with:
          ref: "builds"
          path: "builds"

    - name: Adding some values
      run:
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle


    - name: Build with Gradle
      run: |
        cd $GITHUB_WORKSPACE/src
        chmod +x gradlew
        ./gradlew build
        cp app/build/outputs/apk/release/app-release.apk ../builds/app-release.apk

    - name: Upload APK 
      uses: actions/upload-artifact@v3 
      with: 
          name: app-release
          path: $GITHUB_WORKSPACE/builds/app-release.*
    - name: Push builds
      run: |
        cd $GITHUB_WORKSPACE/builds
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git commit -m "Build ${{ env.sha_short }}" || exit 0   # do not error if nothing to commit
        git push